export const site = {
  nameMr: "प्रीतम ज्येष्ठ नागरिक आनंदशाळा",
  nameEn: "Preetam Senior Citizen Anandshala",
  taglineMr: "ज्येष्ठ नागरिकांच्या निरोगी आरोग्य व आनंददायी आयुष्याचं दार येथेच उघडतं...",
  taglineEn: "The gateway to healthy living and a joyful life for senior citizens...",
  launchMr: "शुभारंभ : २६ जानेवारी २०२६",
  launchEn: "Grand Opening: 26th January 2026",
  phones: ["9370237633", "9423258859", "9970079090"],
  email: "Preetamanandshala@gmail.com",
  website: "www.preetamseniorcitizenanandshala.com",
  addressMr: "सर्वे नंबर 39/1, 2, 3 आनंद नगरी, माधवनगर धनंजय गार्डन रोड, रेल्वे गेट शेजारी, सांगली",
  addressEn: "Survey No. 39/1, 2, 3 Anand Nagari, Madhavnagar Dhananjay Garden Road, Near Railway Gate, Sangli",
  timingMr: "आनंदशाळेची वेळ : सकाळी ११ ते सायं. ५",
  timingEn: "Anandshala Timing: 11:00 AM to 5:00 PM",
  founderMr: "श्री. अभिनय जगन्नाथ कामाजी",
  founderEn: "Shri Abhinay Jagannath Kamaji",
};

export const navLinks = [
  { to: "/", label: "मुख्यपृष्ठ", en: "Home" },
  { to: "/about", label: "आमच्याविषयी", en: "About" },
  { to: "/brochure", label: "माहिती पत्रक", en: "Brochure" },
  { to: "/gallery", label: "गॅलरी", en: "Gallery" },
  { to: "/contact", label: "संपर्क", en: "Contact" },
] as const;

export const facilities = [
  { icon: "🏠", titleMr: "फुल फर्निश्ड निवास", titleEn: "Fully Furnished Living", textMr: "सिंगल, कपल, शेअरिंग, ए.सी. रूम, 1RK व 1BHK पर्याय उपलब्ध.", textEn: "Single, Couple, Sharing, AC Rooms, 1RK and 1BHK options available." },
  { icon: "🍽️", titleMr: "फूड कोर्ट व जेवण", titleEn: "Food Court & Meals", textMr: "अद्ययावत फूड कोर्ट, प्युअर व्हेज हॉटेल, चहा-नाश्ता व सकस जेवण.", textEn: "Modern food court, pure veg restaurant, tea, snacks & nutritious meals." },
  { icon: "🩺", titleMr: "दवाखाना व मेडिकल", titleEn: "Clinic & Medical Care", textMr: "आरोग्य तपासणी, दवाखाना व मेडिकल सुविधा आवारातच.", textEn: "Health checkups, clinic & medical facilities inside campus." },
  { icon: "🏊", titleMr: "स्विमिंग पूल व जीम", titleEn: "Swimming Pool & Gym", textMr: "भव्य स्पोर्ट्स व फिटनेस कॉम्प्लेक्स, बॅडमिंटन, टेनिस, जीम.", textEn: "Grand sports & fitness complex, badminton, tennis, gym." },
  { icon: "🛕", titleMr: "मंदिर व गोशाळा", titleEn: "Temple & Gaushala", textMr: "५५ फुटांची राधाकृष्ण मूर्ती, मंदिर व गोशाळा.", textEn: "55 ft Radha Krishna Statue, Temple & Gaushala." },
  { icon: "📚", titleMr: "वाचनालय व कलाशिक्षण", titleEn: "Library & Arts", textMr: "वाचनालय, कलागुणांना वाव, मानधन व आत्मसन्मान.", textEn: "Library, arts platform, stipend and self-respect." },
  { icon: "🚐", titleMr: "जाणे-येणे सुविधा", titleEn: "Transport Facility", textMr: "स्कूल व्हॅन व ई-रिक्षाने आनंदशाळेत ये-जा करता येते.", textEn: "Van & E-ricksha transport available for commute." },
  { icon: "🎉", titleMr: "सण व वाढदिवस", titleEn: "Festivals & Birthdays", textMr: "सर्व धार्मिक उत्सव, सण व वाढदिवस आनंदाने साजरे.", textEn: "All festivals, religious celebrations and birthdays celebrated with joy." },
];

export const admissionPlans = [
  {
    nameMr: "एक दिवस सहल भेट पास",
    nameEn: "One Day Picnic Pass",
    price: "₹ ६००",
    unitMr: "/ प्रति व्यक्ती",
    unitEn: "/ per person",
    pointsMr: ["वेळ : स. ११ ते सायं. ५", "चहा, नाश्ता व जेवण", "परिसर दर्शन व खेळ", "सर्व सुविधांचा आनंद"],
    pointsEn: ["Timing: 11 AM to 5 PM", "Tea, Snacks & Meals", "Campus Tour & Games", "Access to all amenities"],
    featured: false,
  },
  {
    nameMr: "आनंदनिवास (राहणे सह)",
    nameEn: "Anandnivas (With Stay)",
    price: "₹ ११,०००",
    unitMr: "/ महिना पासून",
    unitEn: "/ month onwards",
    pointsMr: ["राहणे + आनंदशाळा", "नाश्ता २, जेवण २, चहा २", "सर्व उपक्रम व सुविधा", "*GST अतिरिक्त"],
    pointsEn: ["Accommodation + Anandshala", "2 Snacks, 2 Meals, 2 Teas", "All Activities & Amenities", "*GST Extra"],
    featured: true,
  },
  {
    nameMr: "फक्त आनंदशाळा",
    nameEn: "Day Anandshala Only",
    price: "₹ ३,०००",
    unitMr: "/ महिना पासून",
    unitEn: "/ month onwards",
    pointsMr: ["स. ११ ते सायं. ५", "खेळ, कला व उपक्रम", "मित्र-मैत्रिणींसोबत वेळ", "आरोग्यदायी दिनचर्या"],
    pointsEn: ["11 AM to 5 PM", "Games, Arts & Activities", "Time with friends", "Healthy daily routine"],
    featured: false,
  },
];

export const whyPoints = [
  { mr: "मनातील राहून गेलेल्या आवडी-निवडी आनंदाने पूर्ण करण्यासाठी.", en: "To happily fulfill lifelong unfulfilled hobbies and passions." },
  { mr: "मनासारखे आनंदी व स्वावलंबी जीवन जगता येण्यासाठी.", en: "To live a joyful and self-reliant life on your own terms." },
  { mr: "कलागुणांना वाव, मानधन व आत्मसन्मान मिळण्यासाठी.", en: "To showcase artistic talents, earn stipends and gain self-dignity." },
  { mr: "एकटेपणा, नैराश्य व चिडचिड यापासून मुक्ती मिळण्यासाठी.", en: "To overcome loneliness, depression, and stress effortlessly." },
  { mr: "आपल्या वयाच्या मित्र-मैत्रिणींसोबत स्वाभिमानाने जगण्यासाठी.", en: "To live respectfully with like-minded friends of your age group." },
  { mr: "बी.पी., शुगर, टेन्शन कमी करून निरोगी आनंदी जीवनासाठी.", en: "To reduce BP, diabetes, tension for a healthy and joyful life." },
  { mr: "स्वतः कमावलेल्या पैशाचा थोडा तरी स्वतःसाठी उपभोग घेण्यासाठी.", en: "To enjoy hard-earned savings for your own happiness." },
  { mr: "जीवनाची सायंकाळ उत्साहाने, मनसोक्त जगण्यासाठी.", en: "To spend the golden years of life with enthusiasm and joy." },
];

export const sportsClub = {
  nameMr: "प्रीतम स्पोर्ट्स अँड फिटनेस क्लब",
  nameEn: "Preetam Sports & Fitness Club",
  taglineMr: "जिम, बॅडमिंटन, स्विमिंगपूल, पिकलबॉल कोर्ट, योगा, टेबल टेनिस, स्नुकर, स्क्वॅश, मेडिटेशन, झुंबा, डान्स कॉम्प्लिमेंटरी मध्ये बैठे खेळ, वाचनालय, संगीत उपकरण हॉल — मोफत प्रवेश",
  taglineEn: "Gym, Badminton, Swimming Pool, Pickleball Court, Yoga, Table Tennis, Snooker, Squash, Meditation, Zumba, Dance with complimentary Indoor Games, Library & Music Hall access",
  logo: "https://d3k88l35vy59af.cloudfront.net/A42/9336/1760175180579.png",
  timingMr: "क्लबची वेळ : सकाळी ६ ते रात्री ९",
  timingEn: "Club Hours: 6:00 AM to 9:00 PM",
  estYear: "2025",
  natureOfBusinessMr: "स्पोर्ट्स अँड फिटनेस क्लब",
  natureOfBusinessEn: "Sports & Fitness Club",
  founderMr: "श्री. अभिनय जगन्नाथ कामाजी",
  founderEn: "Shri Abhinay Jagannath Kamaji",
  phones: ["+91-9370237633", "+91-9423258859"],
  whatsapp: "https://wa.me/919370237633?text=Got%20reference%20from%20your%20Digital%20vCard.%20Want%20to%20know%20more%20details.",
  email: "Preetamsportclub@gmail.com",
  altEmail: "Preetamanandshala@gmail.com",
  googleMaps: "https://maps.app.goo.gl/KgXVLjLWke5p6PbR7",
  addressMr: "सर्वे नंबर 39/1, 2, 3 आनंद नगरी, माधवनगर धनंजय गार्डन रोड, रेल्वे गेट शेजारी, सांगली",
  addressEn: "Survey No. 39/1, 2, 3 Anand Nagari, Madhavnagar Dhananjay Garden Road, Near Railway Gate, Sangli",
  socials: {
    youtube: "https://www.youtube.com/@PreetamSportsAndFitnessClub",
    facebook: "https://www.facebook.com/preetamseniorcitizenanandshala",
    instagram: "https://www.instagram.com/preetam_sports_fitness_club",
  },
  stats: [
    { value: "२५+", labelMr: "जागतिक दर्जाच्या सुविधा", labelEn: "World-Class Amenities" },
    { value: "१.५ एकर", labelMr: "भव्य स्पोर्ट्स संकुल", labelEn: "Acre Sports Campus" },
    { value: "२०२५", labelMr: "स्थापना वर्ष", labelEn: "Est. Year" },
    { value: "सर्व वयोगट", labelMr: "बालके, तरुण व ज्येष्ठ", labelEn: "For All Age Groups" },
  ],
  specialities: [
    { mr: "मेंबरशिपवर वाचनालय 📚, संगीत हॉल 🎼, बैठे खेळ हॉल आणि भव्य जॉगिंग ट्रॅक 🏃‍♂️ आउटडोअर फिटनेस गार्डन मोफत.", en: "Complimentary Library 📚, Music Hall 🎼, Indoor Games & Jogging Track 🏃‍♂️ with membership." },
    { mr: "सांगलीतील पहिले आणि सर्वात भव्य स्पोर्ट्स अँड फिटनेस क्लब", en: "First & largest Sports & Fitness Club in Sangli district." },
    { mr: "जिम, स्विमिंग, योगा अशा २५+ जागतिक दर्जाच्या सुविधा एकाच छताखाली. 🤸‍♀️", en: "25+ world-class facilities including Gym, Swimming, Yoga under one roof." },
    { mr: "शुद्ध हवा 🌬️ आणि निसर्गरम्य वातावरणात फिटनेस आणि व्यायामाचा आनंद. 🌳", en: "Fitness and exercise in pure air 🌬️ and scenic natural surroundings." },
    { mr: "स्क्वॉश, स्नूकर, टेबल टेनिस 🏓 आणि पिकलबॉल कोर्ट अशा रोमांचक खेळांसाठी सर्वोत्तम ठिकाण.", en: "Best hub for Squash, Snooker, Table Tennis 🏓 and Pickleball." },
    { mr: "मेडिटेशन 🧘, झुंबा आणि डान्स द्वारे शारीरिक व मानसिक आरोग्याचा सुंदर संगम.", en: "Perfect harmony of mind and body through Meditation 🧘, Zumba & Dance." },
    { mr: "श्री. अभिनय जगन्नाथ कामाजी यांच्या संकल्पनेतून साकारलेले सांगलीचे नवीन फिटनेस व स्पोर्ट्स डेस्टिनेशन", en: "Sangli's new sports destination envisioned by Shri Abhinay Jagannath Kamaji." },
    { mr: "फक्त फिटनेस नाही, तर संपूर्ण कुटुंबासाठी आरोग्य, आनंद आणि मनोरंजनाचे केंद्र. 👨‍👩‍👧‍👦", en: "Not just fitness, a complete health and entertainment hub for whole family." },
    { mr: "आजच मेंबरशिप घेऊन आपल्या आरोग्य आणि फिटनेस प्रवासाची आनंदाने व उत्साहाने सुरुवात करा! 🚀", en: "Join membership today and start your joyful health journey! 🚀" },
  ],
  aboutFullMr: `आपण प्रीतम स्पोर्ट्स व फिटनेस क्लब ची मेंबरशिप घेऊन भारतातील प्रथम चालू होत असलेल्या जेष्ठ नागरिक आनंदशाळेला सपोर्ट सहकार्य करा व जेष्ठांचे शुभ आशीर्वाद मिळवा.

सांगली जिल्ह्यातील पहिले आणि सर्वात भव्य स्पोर्ट्स अँड फिटनेस क्लब म्हणून 'प्रीतम स्पोर्ट्स अँड फिटनेस क्लब' आपल्या सेवेत आनंदाने सज्ज आहे! 🎉

आमचा उद्देश केवळ व्यायामशाळा (Gym) चालवणे नाही, तर संपूर्ण आरोग्य, उत्साह आणि आनंदाचे एक केंद्र निर्माण करणे आहे. श्री. अभिनय जगन्नाथ कामाजी यांच्या दूरदृष्टीमुळे, आम्ही एक असे ठिकाण उभे केले आहे, जिथे फिटनेस, खेळ आणि नैसर्गिक शांतता यांचा अद्भुत संगम आहे.

🌿 निसर्गाच्या सानिध्यात आरोग्य: आमचे क्लब हे शहराच्या गजबजाटापासून दूर, शुद्ध हवा 🌬️ आणि हिरवळीच्या निसर्गरम्य वातावरणात स्थित आहे. सदर ठिकाण सांगलीच्या सर्व ठिकाणावरून ५ किलोमीटर च्या आत आहे. येथे व्यायाम करणे म्हणजे केवळ शरीराला ऊर्जा देणे नाही, तर मनालाही शांती आणि ताजेतवाने अनुभव देणे आहे. आमच्या प्रशस्त जॉगिंग ट्रॅक 👟, सुंदर लॉन आणि ओपन स्पेसमुळे प्रत्येक सकाळ उत्साहाने सुरू होते.

🥇 सुविधांचा भव्य अनुभव: आम्ही एकाच छताखाली २५ हून अधिक जागतिक दर्जाच्या फिटनेस आणि खेळांच्या सुविधा उपलब्ध करून दिल्या आहेत.

✨ कॉम्प्लिमेंटरी आनंदाचे केंद्र: वाचनालय (Library), संगीत उपकरण हॉल, व कॅरम-बुद्धीबळ बैठे खेळ मोफत!`,
  aboutFullEn: `Support India's first Senior Citizen Anandshala by joining membership of Preetam Sports & Fitness Club and receive divine blessings of elders.

Preetam Sports & Fitness Club is proudly ready to serve as the first and largest sports & fitness complex in Sangli district! 🎉

Our aim is not merely running a gym, but creating a sanctuary of health, vigor, and joy. Envisioned by Shri Abhinay Jagannath Kamaji, we have built a destination where fitness, sports, and natural serenity blend harmoniously.

🌿 Health in Nature: Located away from city rush with pure air 🌬️ and green surroundings within 5 km from anywhere in Sangli. Jogging tracks 👟, open lawns, and peaceful spaces make every morning energetic.

🥇 Grand Facilities: 25+ world-class sports & fitness amenities under one roof including Gym, Swimming Pool, Badminton, Pickleball, Yoga & Meditation.

✨ Complimentary Perks: Free access to Library 📚, Music Hall 🎼, and Indoor Games (Carrom, Chess) with membership!`,
  facilities: [
    {
      id: "gym",
      icon: "💪",
      titleMr: "अत्याधुनिक जिम (State-of-the-Art Gym)",
      titleEn: "State-of-the-Art Gym",
      descMr: "जागतिक दर्जाची कार्डिओ 🏃‍♀️, वेट ट्रेनिंग 🏋️ आणि स्ट्रेंथ इक्विपमेंट्स उपलब्ध. तज्ज्ञ प्रशिक्षकांचे मार्गदर्शन.",
      descEn: "World-class cardio 🏃‍♀️, weight training 🏋️ & strength equipment available with certified trainers.",
      specsMr: [
        "🌐 सुविधा: आंतरराष्ट्रीय दर्जाचे कार्डिओ आणि वेट लिफ्टिंग उपकरणे.",
        "🧑‍🏫 मार्गदर्शन: प्रमाणित आणि अनुभवी प्रशिक्षक नेहमी मदतीसाठी उपलब्ध.",
        "⏰ लवचिकता: तुमच्या वेळेनुसार सोयीस्कर बॅच आणि ट्रेनिंग वेळापत्रक.",
        "🎯 फोकस: स्नायूंची वाढ, वजन कमी करणे आणि एकूण तंदुरुस्ती.",
      ],
      specsEn: [
        "🌐 Amenities: International standard cardio & strength gear.",
        "🧑‍🏫 Guidance: Certified and experienced fitness trainers.",
        "⏰ Flexibility: Convenient batches matching your schedule.",
        "🎯 Focus: Muscle gain, weight loss & overall fitness.",
      ],
      images: [
        "https://d3k88l35vy59af.cloudfront.net/A42/9663/1763184848892.jpg",
        "https://d3k88l35vy59af.cloudfront.net/A42/9663/1763184843273.jpg",
        "https://d3k88l35vy59af.cloudfront.net/A42/9663/1763184838684.jpg",
        "https://d3k88l35vy59af.cloudfront.net/A42/9663/1763184833833.jpg",
      ],
      whatsapp: "https://wa.me/919370237633?text=Hi,%20I%20am%20interested%20in%20your%20Gym%20facility.",
    },
    {
      id: "yoga",
      icon: "🧘",
      titleMr: "योगा स्टुडिओ (Yoga Studio)",
      titleEn: "Yoga Studio",
      descMr: "शरीर आणि मन यांच्यातील सुंदर समन्वय अनुभवा. प्राणायाम, ध्यान आणि आसने शिकण्यासाठी आदर्श जागा.",
      descEn: "Experience harmony of mind and body. Ideal studio for Pranayama, Meditation & Asanas.",
      specsMr: [
        "🧘 फायदे: लवचिकता, मनःशांती आणि तणावमुक्ती.",
        "🙏 प्रकार: हठ योग, पॉवर योग आणि मेडिटेटिव्ह योगाचे क्लासेस.",
        "✨ वातावरण: शांत, नैसर्गिक आणि सकारात्मक ऊर्जा देणारे.",
      ],
      specsEn: [
        "🧘 Benefits: Flexibility, peace of mind & stress relief.",
        "🙏 Types: Hatha Yoga, Power Yoga & Meditative Yoga.",
        "✨ Ambience: Peaceful, natural & positive environment.",
      ],
      images: [
        "https://d3k88l35vy59af.cloudfront.net/A42/9663/1763188841664.jpg",
        "https://d3k88l35vy59af.cloudfront.net/A42/9663/1763188841665.jpg",
        "https://d3k88l35vy59af.cloudfront.net/A42/9663/1763188841666.jpg",
      ],
      whatsapp: "https://wa.me/919370237633?text=Hi,%20I%20am%20interested%20in%20Yoga%20Studio.",
    },
    {
      id: "meditation",
      icon: "🕊️",
      titleMr: "मेडिटेशन (ध्यान) कक्ष (Meditation Room)",
      titleEn: "Meditation Room",
      descMr: "धावपळीच्या जीवनात मनाला विश्रांती देण्यासाठी समर्पित मेडिटेशन कक्ष.",
      descEn: "Dedicated peaceful meditation hall to relax and recharge your mind.",
      specsMr: [
        "💡 उद्देश: मानसिक शांती, एकाग्रता आणि तणाव कमी करणे.",
        "✨ वैशिष्ट्य: शांतता आणि एकाग्रतेसाठी डिझाइन केलेला विशेष कक्ष.",
        "🧠 लाभ: मनःस्थिती सुधारण्यास आणि स्मरणशक्ती वाढवण्यास मदत.",
      ],
      specsEn: [
        "💡 Purpose: Mental peace, focus & stress relief.",
        "✨ Feature: Specially acoustic design for quietness.",
        "🧠 Benefits: Elevates mood and memory retention.",
      ],
      images: [
        "https://d3k88l35vy59af.cloudfront.net/A42/9663/1763203091441.jpg",
        "https://d3k88l35vy59af.cloudfront.net/A42/9663/1763203091442.jpg",
        "https://d3k88l35vy59af.cloudfront.net/A42/9663/1763203091443.jpg",
        "https://d3k88l35vy59af.cloudfront.net/A42/9663/1763203091444.jpg",
      ],
      whatsapp: "https://wa.me/919370237633?text=Hi,%20I%20am%20interested%20in%20Meditation%20Room.",
    },
    {
      id: "zumba",
      icon: "💃",
      titleMr: "झुंबा क्लासेस (Zumba Classes)",
      titleEn: "Zumba Dance Classes",
      descMr: "संगीताच्या तालावर डान्स करत कॅलरी बर्न करा आणि मज्जा करा!",
      descEn: "Burn calories with joyful music & high-energy dance workout sessions!",
      specsMr: [
        "🥳 अनुभव: फिटनेस आणि डान्स पार्टीचा जबरदस्त अनुभव.",
        "🔥 परिणाम: वेगाने कॅलरी बर्न आणि संपूर्ण शरीराचा व्यायाम.",
        "🎶 प्रशिक्षक: उत्साही आणि प्रशिक्षित झुंबा प्रशिक्षकांचे मार्गदर्शन.",
      ],
      specsEn: [
        "🥳 Vibe: Party like dance fitness experience.",
        "🔥 Outcome: Rapid calorie burn & full body workout.",
        "🎶 Instructors: Energetic certified Zumba trainers.",
      ],
      images: [
        "https://d3k88l35vy59af.cloudfront.net/A42/9663/1763357581614.png",
        "https://d3k88l35vy59af.cloudfront.net/A42/9663/1763357577652.png",
        "https://d3k88l35vy59af.cloudfront.net/A42/9663/1763357572624.png",
      ],
      whatsapp: "https://wa.me/919370237633?text=Hi,%20I%20am%20interested%20in%20Zumba%20Classes.",
    },
    {
      id: "dance",
      icon: "👯",
      titleMr: "डान्स क्लासेस (Dance Classes)",
      titleEn: "Dance Academy",
      descMr: "बॉलीवूड, हिप-हॉप, फ्रीस्टाइल प्रकार शिकून कलागुणांना वाव द्या.",
      descEn: "Learn Bollywood, Hip-Hop & Freestyle dance from expert dance gurus.",
      specsMr: [
        "🩰 प्रकार: बॉलीवूड, फ्रीस्टाइल, कंटेम्पररी यांसारखे विविध नृत्य प्रकार.",
        "💖 फायदे: लवचिकता वाढवणे आणि आत्मविश्वास सुधारणे.",
        "👩‍🏫 शिकणे: खास प्रशिक्षित नृत्य शिक्षकांकडून धडे.",
      ],
      specsEn: [
        "🩰 Styles: Bollywood, Freestyle & Contemporary forms.",
        "💖 Benefits: Enhances flexibility & self-confidence.",
        "👩‍🏫 Coaching: Professional guidance by dance gurus.",
      ],
      images: [
        "https://d3k88l35vy59af.cloudfront.net/A42/9663/1763203444303.jpg",
        "https://d3k88l35vy59af.cloudfront.net/A42/9663/1763203444304.jpg",
        "https://d3k88l35vy59af.cloudfront.net/A42/9663/1763203444305.jpg",
        "https://d3k88l35vy59af.cloudfront.net/A42/9663/1763203444306.jpg",
      ],
      whatsapp: "https://wa.me/919370237633?text=Hi,%20I%20am%20interested%20in%20Dance%20Classes.",
    },
    {
      id: "swimming",
      icon: "🏊",
      titleMr: "भव्य स्विमिंग पूल (Grand Swimming Pool)",
      titleEn: "Grand Swimming Pool",
      descMr: "स्वच्छ व मोठा स्विमिंग पूल. मुलांसाठी व मोठ्यांसाठी कोचिंग सुलभ.",
      descEn: "Crystal clear grand swimming pool with trainers & lifeguards for all ages.",
      specsMr: [
        "💧 स्वच्छता: नियमित फिल्टरिंग आणि गुणवत्ता तपासणी.",
        "👨‍🎓 प्रशिक्षण: नवशिक्यांसाठी आणि मुलांसाठी पोहण्याचे खास क्लासेस.",
        "🌞 अनुभव: संपूर्ण शरीरासाठी प्रभावी आणि आनंददायी व्यायाम.",
      ],
      specsEn: [
        "💧 Hygiene: Continuous water filtration & quality test.",
        "👨‍🎓 Coaching: Swimming classes for kids and adults.",
        "🌞 Impact: Complete low-impact full body cardio.",
      ],
      images: [
        "https://d3k88l35vy59af.cloudfront.net/A42/9663/1762243460172.jpg",
        "https://d3k88l35vy59af.cloudfront.net/A42/9336/1761815943159.jpg",
        "https://d3k88l35vy59af.cloudfront.net/A42/9336/1760177990367.jpeg",
      ],
      whatsapp: "https://wa.me/919370237633?text=Hi,%20I%20am%20interested%20in%20Swimming%20Pool.",
    },
    {
      id: "badminton",
      icon: "🏸",
      titleMr: "बॅडमिंटन कोर्ट (Badminton Courts)",
      titleEn: "Indoor Badminton Courts",
      descMr: "आंतरराष्ट्रीय मानकांचे उच्च-गुणवत्तेचे वूडन व मॅट कोर्ट्स.",
      descEn: "International standard wooden and mat flooring courts with anti-glare lighting.",
      specsMr: [
        "🏆 दर्जा: आंतरराष्ट्रीय मानकांचे उच्च-गुणवत्तेचे कोर्ट्स.",
        "💡 लाईटिंग: खेळासाठी योग्य आणि डोळ्यांना आरामदायक प्रकाशयोजना.",
        "🤝 उपलब्धता: कोर्ट बुकिंग आणि मासिक मेंबरशिप पर्याय उपलब्ध.",
      ],
      specsEn: [
        "🏆 Quality: Wooden & synthetic mat professional courts.",
        "💡 Lighting: Tournament grade eye-friendly LED lights.",
        "🤝 Booking: Hourly court slots & monthly memberships.",
      ],
      images: [
        "https://d3k88l35vy59af.cloudfront.net/A42/9663/1763203979535.jpg",
        "https://d3k88l35vy59af.cloudfront.net/A42/9663/1763203969471.jpg",
        "https://d3k88l35vy59af.cloudfront.net/A42/9663/1763203952737.jpg",
        "https://d3k88l35vy59af.cloudfront.net/A42/9663/1763203942143.jpg",
      ],
      whatsapp: "https://wa.me/919370237633?text=Hi,%20I%20am%20interested%20in%20Badminton%20Courts.",
    },
    {
      id: "squash",
      icon: "🎾",
      titleMr: "स्क्वॉश कोर्ट (Squash Court)",
      titleEn: "Squash Court",
      descMr: "उच्च वेगाच्या व ऊर्जा-खर्चीक खेळासाठी आंतरराष्ट्रीय स्क्वॉश कोर्ट.",
      descEn: "High-speed intense cardio racquet sport court for agility and stamina.",
      specsMr: [
        "⚡️ वेग: उच्च वेगाच्या आणि तीव्र व्यायामासाठी उत्तम.",
        "💪 लाभ: हृदय व रक्तवाहिन्यासंबंधी (Cardiovascular) आरोग्य सुधारते.",
        "🔑 बुकिंग: सोयीनुसार तासावर कोर्ट बुकिंगची सोय.",
      ],
      specsEn: [
        "⚡️ Pace: High intensity fast racquet sport.",
        "💪 Fitness: Boosts cardiovascular stamina.",
        "🔑 Access: Flexible court booking options.",
      ],
      images: [
        "https://d3k88l35vy59af.cloudfront.net/A42/9663/1763206382917.jpg",
        "https://d3k88l35vy59af.cloudfront.net/A42/9663/1763206382918.jpg",
        "https://d3k88l35vy59af.cloudfront.net/A42/9663/1763206382919.jpg",
      ],
      whatsapp: "https://wa.me/919370237633?text=Hi,%20I%20am%20interested%20in%20Squash%20Court.",
    },
    {
      id: "tabletennis",
      icon: "🏓",
      titleMr: "टेबल टेनिस हॉल (Table Tennis Hall)",
      titleEn: "Table Tennis Hall",
      descMr: "रोमांचक टेबल टेनिस खेळासाठी उच्च दर्जाचे टेबल्स व पॅडल्स.",
      descEn: "Pro grade table tennis setup for sharpen focus and quick reflexes.",
      specsMr: [
        "🎯 फोकस: एकाग्रता आणि प्रतिक्रिया गती सुधारते.",
        "✅ उपकरणे: उच्च-गुणवत्तेचे टीटी टेबल्स आणि साहित्य.",
        "🕹️ अनुभव: शांत आणि उत्साही वातावरणात खेळण्याचा आनंद.",
      ],
      specsEn: [
        "🎯 Reflexes: Sharpens concentration and reaction time.",
        "✅ Gear: Tournament level TT tables & balls.",
        "🕹️ Ambience: Spacious and well-lit playing area.",
      ],
      images: [
        "https://d3k88l35vy59af.cloudfront.net/A42/9663/1763206867693.jpg",
        "https://d3k88l35vy59af.cloudfront.net/A42/9663/1763206867694.jpg",
        "https://d3k88l35vy59af.cloudfront.net/A42/9663/1763206867695.jpg",
      ],
      whatsapp: "https://wa.me/919370237633?text=Hi,%20I%20am%20interested%20in%20Table%20Tennis.",
    },
    {
      id: "snooker",
      icon: "🎱",
      titleMr: "स्नूकर आणि पूल (Snooker and Pool)",
      titleEn: "Snooker & Pool Lounge",
      descMr: "एकाग्रता वाढवणारा स्नूकर आणि विरंगुळ्यासाठी पूल टेबल्स.",
      descEn: "Premium billiard tables to unwind, focus and enjoy strategic games with friends.",
      specsMr: [
        "🧠 कौशल्य: अचूकता, एकाग्रता आणि धोरणात्मक विचार वाढवते.",
        "<ctrl42> सुविधा: आरामदायक बैठक व्यवस्था आणि शांत वातावरण.",
        "👍 उद्देश: सामाजिक आणि मनोरंजक विरंगुळ्यासाठी उत्तम.",
      ],
      specsEn: [
        "🧠 Skill: Improves precision and tactical thinking.",
        "🛋️ Lounge: Comfortable seating & air conditioned room.",
        "👍 Recreation: Great social hangout sport.",
      ],
      images: [
        "https://d3k88l35vy59af.cloudfront.net/A42/9663/1762243482819.jpg",
        "https://d3k88l35vy59af.cloudfront.net/A42/9336/1761816054100.jpg",
        "https://d3k88l35vy59af.cloudfront.net/A42/9336/1760115460449.png",
      ],
      whatsapp: "https://wa.me/919370237633?text=Hi,%20I%20am%20interested%20in%20Snooker%20and%20Pool.",
    },
    {
      id: "pickleball",
      icon: "🥅",
      titleMr: "पिकलबॉल कोर्ट मैदान (Artificial Turf Field)",
      titleEn: "Pickleball & Turf Ground",
      descMr: "आधुनिक कृत्रिम टर्फ मैदान, पिकलबॉल, फुटबॉल व क्रिकेट सरावासाठी.",
      descEn: "High-grade artificial turf court for Pickleball, mini Football & Cricket matches.",
      specsMr: [
        "🌿 गुणवत्ता: उच्च-गुणवत्तेचे आणि सुरक्षित कृत्रिम टर्फ.",
        "📅 बुकिंग: टीम मॅच आणि सरावासाठी तासावर भाड्याने उपलब्ध.",
        "🎮 वापर: पिकलबॉल, फुटबॉल, क्रिकेट आणि इतर मैदानी खेळांसाठी.",
      ],
      specsEn: [
        "🌿 Turf: Safe shock-absorbing synthetic grass turf.",
        "📅 Slot Booking: Hourly rental for team matches & practice.",
        "🎮 Multi-sport: Pickleball, Football, Cricket & Warmups.",
      ],
      images: [
        "https://d3k88l35vy59af.cloudfront.net/A42/9663/1763202416442.jpg",
        "https://d3k88l35vy59af.cloudfront.net/A42/9663/1763202393807.jpg",
        "https://d3k88l35vy59af.cloudfront.net/A42/9663/1763202037643.jpg",
        "https://d3k88l35vy59af.cloudfront.net/A42/9663/1763201883062.jpg",
        "https://d3k88l35vy59af.cloudfront.net/A42/9663/1763201883063.jpg",
      ],
      whatsapp: "https://wa.me/919370237633?text=Hi,%20I%20am%20interested%20in%20Pickleball%20and%20Turf.",
    },
    {
      id: "jogging",
      icon: "👟",
      titleMr: "जॉगिंग ट्रॅक (Jogging Track)",
      titleEn: "Jogging & Walking Track",
      descMr: "हिरवळीच्या निसर्गरम्य वातावरणात सुरक्षित व प्रशस्त जॉगिंग ट्रॅक.",
      descEn: "Spacious scenic jogging track amidst lush greenery and fresh air.",
      specsMr: [
        "🏞️ वातावरण: शुद्ध हवा आणि निसर्गाच्या सानिध्यात ट्रॅक.",
        "✅ सुरक्षितता: सुरक्षित आणि वाहनांपासून मुक्त ट्रॅक.",
        "💖 फायदा: सकाळच्या व संध्याकाळच्या कार्डिओसाठी आदर्श.",
      ],
      specsEn: [
        "🏞️ Atmosphere: Pure air surrounded by nature.",
        "✅ Safety: Vehicle free safe running track.",
        "💖 Routine: Perfect for morning & evening walk.",
      ],
      images: [
        "https://d3k88l35vy59af.cloudfront.net/A42/9336/1760166322502.jpeg",
        "https://d3k88l35vy59af.cloudfront.net/A42/9336/1760166317653.jpeg",
        "https://d3k88l35vy59af.cloudfront.net/A42/9029/1759815501929.png",
      ],
      whatsapp: "https://wa.me/919370237633?text=Hi,%20I%20am%20interested%20in%20Jogging%20Track.",
    },
    {
      id: "opengym",
      icon: "🏋️‍♂️",
      titleMr: "ओपन जिम (Open Gym)",
      titleEn: "Outdoor Open Gym",
      descMr: "खुल्या वातावरणात बॉडीवेट व ॲथलेटिक व्यायामासाठी ओपन जिम.",
      descEn: "Outdoor fitness equipment setup for free weights & bodyweight workout.",
      specsMr: [
        "💪 उपकरणे: अत्याधुनिक ओपन जिम मशीन.",
        "🕒 सोय: सदस्यांसाठी मोकळेपणाने वापरण्याची सोय.",
        "🤝 सपोर्ट: निसर्गरम्य वातावरणात कसरत.",
      ],
      specsEn: [
        "💪 Gear: All-weather outdoor workout machinery.",
        "🕒 Access: Open all day for club members.",
        "🤝 Benefit: Enjoy workouts in refreshing natural breeze.",
      ],
      images: [
        "https://d3k88l35vy59af.cloudfront.net/A42/9663/1762243539238.jpg",
        "https://d3k88l35vy59af.cloudfront.net/A42/9663/1762243539239.jpg",
        "https://d3k88l35vy59af.cloudfront.net/A42/9336/1760274358794.jpg",
      ],
      whatsapp: "https://wa.me/919370237633?text=Hi,%20I%20am%20interested%20in%20Open%20Gym.",
    },
    {
      id: "lawn",
      icon: "🌿",
      titleMr: "लॉन (Lawn)",
      titleEn: "Green Lawns",
      descMr: "स्ट्रेचिंग, योग व फॅमिली टाइमसाठी निसर्गरम्य हिरवळीचे लॉन.",
      descEn: "Sprawling manicured green lawn for group yoga, stretching & picnics.",
      specsMr: [
        "🌞 सुविधा: खुला, हिरवळीत भरलेला सुंदर परिसर.",
        "🧘 उपयोग: योग, फिटनेस सत्र, इव्हेंट्स आणि विश्रांती.",
        "🤝 सोय: मेंबर आणि बुकिंग पर्याय उपलब्ध.",
      ],
      specsEn: [
        "🌞 Environment: Beautiful open green grass lawn.",
        "🧘 Usage: Group sessions, events & relaxing walks.",
        "🤝 Booking: Event & picnic reservations available.",
      ],
      images: [
        "https://d3k88l35vy59af.cloudfront.net/A42/9336/1760461871266.jpg",
        "https://d3k88l35vy59af.cloudfront.net/A42/9336/1760461871267.jpg",
      ],
      whatsapp: "https://wa.me/919370237633?text=Hi,%20I%20am%20interested%20in%20Lawn.",
    },
    {
      id: "children",
      icon: "🎠",
      titleMr: "चिल्ड्रन्स प्ले एरिया (Children's Play Area)",
      titleEn: "Children's Play Zone",
      descMr: "लहान मुलांसाठी सुरक्षित, रंगीबेरंगी स्विंग्स व खेळांची साधने.",
      descEn: "Safe and colorful kids play zone equipped with slides, swings & games.",
      specsMr: [
        "🌈 सुविधा: स्लाइड्स, स्विंग्स, झुला आणि इतर साधने.",
        "🛡️ सुरक्षा: मुलांसाठी सुरक्षित व नियंत्रित परिसर.",
        "🤝 सोय: पालकांसाठी आरामदायी बसण्याची सोय.",
      ],
      specsEn: [
        "🌈 Rides: Swings, slides & climbing frames.",
        "🛡️ Safety: Soft flooring & secured enclosed area.",
        "🤝 Seating: Parent lounge nearby to supervise.",
      ],
      images: [
        "https://d3k88l35vy59af.cloudfront.net/A42/9663/1763209644300.jpg",
        "https://d3k88l35vy59af.cloudfront.net/A42/9663/1763209631568.jpg",
      ],
      whatsapp: "https://wa.me/919370237633?text=Hi,%20I%20am%20interested%20in%20Children%20Play%20Area.",
    },
  ],
  gallery: [
    "https://d3k88l35vy59af.cloudfront.net/A42/9663/1763357638128.jpg",
    "https://d3k88l35vy59af.cloudfront.net/A42/9663/1763357638129.jpg",
    "https://d3k88l35vy59af.cloudfront.net/A42/9663/1763357638130.png",
    "https://d3k88l35vy59af.cloudfront.net/A42/9663/1763357638131.png",
    "https://d3k88l35vy59af.cloudfront.net/A42/9663/1763357638132.png",
    "https://d3k88l35vy59af.cloudfront.net/A42/9663/1763360651034.jpg",
    "https://d3k88l35vy59af.cloudfront.net/A42/9663/1763360651035.jpg",
    "https://d3k88l35vy59af.cloudfront.net/A42/9663/1763360651036.jpg",
    "https://d3k88l35vy59af.cloudfront.net/A42/9663/1763360651037.jpg",
    "https://d3k88l35vy59af.cloudfront.net/A42/9663/1763360651040.jpg",
    "https://d3k88l35vy59af.cloudfront.net/A42/9663/1763360651042.jpg",
    "https://d3k88l35vy59af.cloudfront.net/A42/9663/1763360651043.jpg",
    "https://d3k88l35vy59af.cloudfront.net/A42/9663/1763360651044.jpg",
    "https://d3k88l35vy59af.cloudfront.net/A42/9663/1763360651045.jpg",
    "https://d3k88l35vy59af.cloudfront.net/A42/9663/1763360688384.png",
    "https://d3k88l35vy59af.cloudfront.net/A42/9663/1763360688385.png",
    "https://d3k88l35vy59af.cloudfront.net/A42/9663/1763360688386.png",
    "https://d3k88l35vy59af.cloudfront.net/A42/9663/1763360688387.jpg",
    "https://d3k88l35vy59af.cloudfront.net/A42/9663/1763360688388.jpg",
    "https://d3k88l35vy59af.cloudfront.net/A42/9663/1763360688389.jpg",
  ],
};